language: java
jdk: oraclejdk8
install:
    mvn --settings travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
    - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
deploy:
  provider: script
  script: make travis-deploy
  on:
    tags: true
